### ISSUE TITLE
Package/dependencies vulnerabilities

### ISSUE THREAD

**Issue by jjperezaguinaga** [MyBitFoundation/MyBit-SDK#27]
We need to update our dependencies to fix the reported vulnerabilities.

So far they are being displayed only on `CodeCoverage/package-lock.json`, but might worth to ensure and check all our dependency related files.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x62234e28a159206b50a2bc3e101c0417a5b837dbeb42732d33caef5ea3e37e4b](https://etherscan.io/tx/0x62234e28a159206b50a2bc3e101c0417a5b837dbeb42732d33caef5ea3e37e4b)

**Comment by kyledewy** [comment]
I believe this is resolved now.
